/* =====================================================================
   小小醫院 2 — 介面字串翻譯檔

   zh：中文原文，tw 空白時的 fallback
   tw：台文漢字（教育部推薦用字）
   lo：台羅

   {n} 會在遊戲中替換成數字，翻譯時請保留。
   ===================================================================== */

const STRINGS = {
  /* 介面 */
  title:         { zh: '小小醫院 2', tw: '小小病院 2', lo: 'Sió-sió Pēnn-īnn 2' },
  hearts:        { zh: '愛心', tw: '愛心', lo: 'ài-sim' },
  day:           { zh: '第 {n} 天', tw: '第 {n} 工', lo: 'tē {n} kang' },
  waiting:       { zh: '候診區', tw: '候診區', lo: 'hāu-tsín-khu' },
  reception:     { zh: '櫃台', tw: '櫃台', lo: 'kuī-tâi' },
  checkStation:  { zh: '檢查台', tw: '檢查台', lo: 'kiám-tsa-tâi' },
  pharmacy:      { zh: '藥局', tw: '藥房', lo: 'io̍h-pâng' },
  gallery:       { zh: '患者名冊', tw: '患者名冊', lo: 'huān-tsiá miâ-tsheh' },
  galleryClose:  { zh: '關閉患者名冊', tw: '關患者名冊', lo: 'kuinn huān-tsiá miâ-tsheh' },
  mysteryPatient:{ zh: '神祕病人', tw: '神祕患者', lo: 'sîn-pì huān-tsiá' },
  visitCount:    { zh: '來訪 {n} 次', tw: '來過 {n} 擺', lo: 'lâi--kuè {n} pái' },
  languageMark:  { zh: '文', tw: '文', lo: 'bûn' },
  languageZh:    { zh: '中文', tw: '華語', lo: 'Huâ-gí' },
  languageTw:    { zh: '台文', tw: '台語', lo: 'Tâi-gí' },
  language:      { zh: '切換語言', tw: '換語言', lo: 'uānn gí-giân' },
  soundOn:       { zh: '開啟音效', tw: '開聲音', lo: 'khui siann-im' },
  soundOff:      { zh: '關閉音效', tw: '聲音禁掉', lo: 'siann-im kìm-tiāu' },
  github:        { zh: 'GitHub', tw: '', lo: '' },
  comfort:       { zh: '拍拍安撫', tw: '搭搭惜惜', lo: 'tah-tah sioh-sioh' },
  closed:        { zh: '醫院休息中', tw: '病院歇睏中', lo: 'pēnn-īnn hioh-khùn tiong' },
  restHint:      { zh: '醫生的眼睛也要休息', tw: '醫生的目睭嘛予歇睏', lo: 'i-sing ê ba̍k-tsiu mā ài hioh-khùn' },
  openHospital:  { zh: '開診', tw: '開診', lo: 'khui-tsín' },
  nextDay:       { zh: '下一天', tw: '後一工', lo: 'āu tsi̍t kang' },
  dayDone:       { zh: '今天下班了！', tw: '今仔日煞工矣！', lo: 'Kin-á-ji̍t suah-kang--ah!' },
  treatedHuman:  { zh: '治好的人：{n}', tw: '醫好的人：{n}', lo: 'i-hó ê lâng: {n}' },
  treatedAnimal: { zh: '治好的動物：{n}', tw: '醫好的動物：{n}', lo: 'i-hó ê tōng-bu̍t: {n}' },
  treatedRobot:  { zh: '修好的機器人：{n}', tw: '修理好的機器人：{n}', lo: 'siu-lí hó ê ki-khì-lâng: {n}' },
  unlocked:      { zh: '新朋友來了！', tw: '新朋友來矣！', lo: 'Sin pîng-iú lâi--ah!' },
  newDept:       { zh: '新門診開了！', tw: '新門診開矣！', lo: 'Sin mn̂g-tsín khui--ah!' },

  /* 科別 */
  internal:      { zh: '內科', tw: '內科', lo: 'lāi-kho' },
  ent:           { zh: '耳鼻喉科', tw: '耳鼻喉科', lo: 'hīnn-phīnn-âu-kho' },
  dental:        { zh: '牙科', tw: '齒科', lo: 'khí-kho' },
  surgery:       { zh: '外科', tw: '外科', lo: 'guā-kho' },
  tcm:           { zh: '中醫', tw: '漢醫', lo: 'hàn-i' },
  vet:           { zh: '獸醫', tw: '獸醫', lo: 'siù-i' },
  repair:        { zh: '維修站', tw: '修理站', lo: 'siu-lí-tsām' },

  /* 症狀 */
  fever:         { zh: '發燒', tw: '發燒', lo: 'huat-sio' },
  cold:          { zh: '感冒', tw: '感冒', lo: 'kám-mōo' },
  gastro:        { zh: '腸胃炎', tw: '胃腸炎', lo: 'uī-tn̂g-iām' },
  runny_nose:    { zh: '流鼻水', tw: '流鼻水', lo: 'lâu phīnn-tsuí' },
  nosebleed:     { zh: '流鼻血', tw: '流鼻血', lo: 'lâu phīnn-huih' },
  cavity:        { zh: '蛀牙', tw: '蛀齒', lo: 'tsiù-khí' },
  scrape:        { zh: '擦傷', tw: '遛皮', lo: 'liù-phuê' },
  fracture:      { zh: '骨折', tw: '骨斷', lo: 'kut-tn̄g' },
  backache:      { zh: '腰痠', tw: '腰痠', lo: 'io sng' },
  bottom_pain:   { zh: '屁股痛', tw: '尻川疼', lo: 'kha-tshng thiànn' },
  pet_fever:     { zh: '發燒', tw: '發燒', lo: 'huat-sio' },
  pet_tummy:     { zh: '肚子痛', tw: '腹肚疼', lo: 'pak-tóo thiànn' },
  pet_scrape:    { zh: '擦傷', tw: '遛皮', lo: 'liù-phuê' },
  pet_cold:      { zh: '感冒', tw: '感冒', lo: 'kám-mōo' },
  pet_cavity:    { zh: '蛀牙', tw: '蛀齒', lo: 'tsiù-khí' },
  pet_fleas:     { zh: '長跳蚤', tw: '生虼蚤', lo: 'senn ka-tsáu' },
  loose_screw:   { zh: '螺絲鬆了', tw: '螺絲鬆去', lo: 'lôo-si sang--khì' },
  stuck_gear:    { zh: '卡卡的', tw: '㧎㧎', lo: 'khê-khê' },
  low_battery:   { zh: '沒電了', tw: '無電矣', lo: 'bô tiān--ah' },

  /* 檢查工具 */
  thermometer:   { zh: '溫度計', tw: '磅針', lo: 'pōng-tsiam' },
  stethoscope:   { zh: '聽診器', tw: '聽筒', lo: 'thiann-tâng' },
  flashlight:    { zh: '手電筒', tw: '手電仔', lo: 'tshiú-tiān-á' },
  magnifier:     { zh: '放大鏡', tw: '譀鏡', lo: 'hàm-kiànn' },
  xray:          { zh: 'X 光', tw: '電光', lo: 'tiān-kong' },
  detector:      { zh: '檢波器', tw: '檢波器', lo: 'kiám-pho-khì' },
  wrench_tap:    { zh: '敲敲看', tw: '硞硞咧', lo: 'kho̍k-kho̍k--leh' },
  battery_meter: { zh: '電池檢測器', tw: '電池檢測器', lo: 'tiān-tî kiám-tshik-khì' },

  /* 治療工具 */
  icepack:       { zh: '冰枕', tw: '冰枕', lo: 'ping-tsím' },
  spray:         { zh: '噴劑', tw: '噴劑', lo: 'phùn-tse' },
  heat_bag:      { zh: '熱敷袋', tw: '水龜', lo: 'tsuí-ku' },
  tissue:        { zh: '面紙', tw: '棉仔紙', lo: 'mî-á-tsuá' },
  cotton:        { zh: '止血棉', tw: '止血棉', lo: 'tsí-huih-mî' },
  toothbrush:    { zh: '牙刷', tw: '齒抿仔', lo: 'khí-bín-á' },
  bandage:       { zh: 'OK 繃', tw: 'OK貼', lo: 'óo-khé-tah' },
  cast:          { zh: '石膏', tw: '石膏', lo: 'tsio̍h-ko' },
  heat_patch:    { zh: '熱敷貼布', tw: '焐燒thè-phù', lo: 'ù-sio thè-phù' },
  donut_cushion: { zh: '甜甜圈坐墊', tw: '甜箍麭椅苴仔', lo: 'tinn-khoo-pháng í-tsū-á' },
  vet_icepack:   { zh: '冰枕', tw: '冰枕', lo: 'ping-tsím' },
  vet_medicine:  { zh: '藥水', tw: '藥水', lo: 'io̍h-tsuí' },
  vet_bandage:   { zh: 'OK 繃', tw: 'OK貼', lo: 'óo-khé-tah' },
  vet_tissue:    { zh: '面紙', tw: '棉仔紙', lo: 'mî-á-tsuá' },
  vet_toothbrush:{ zh: '牙刷', tw: '齒抿仔', lo: 'khí-bín-á' },
  screwdriver:   { zh: '螺絲起子', tw: 'loo-lái-bah', lo: 'loo-lái-bah' },
  wrench:        { zh: '扳手', tw: '扳仔', lo: 'pán-á' },
  charger:       { zh: '充電線', tw: '充電線', lo: 'tshiong-tiān-suànn' },

  /* 藥品 */
  fever_syrup:   { zh: '退燒藥水', tw: '退燒藥水', lo: 'thè-sio io̍h-tsuí' },
  cough_syrup:   { zh: '咳嗽糖漿', tw: '咳嗽藥水', lo: 'ka-sàu io̍h-tsuí' },
  stomach_pill:  { zh: '腸胃藥', tw: '胃腸藥', lo: 'uī-tn̂g io̍h' },
  allergy_syrup: { zh: '抗過敏藥水', tw: '過敏藥水', lo: 'kuè-bín io̍h-tsuí' },
  vitamin:       { zh: '維他命', tw: '維他命', lo: 'uî-thann-bīng' },
  mouthwash:     { zh: '漱口水', tw: '漉喙水', lo: 'lo̍k-tshuì-tsuí' },
  ointment:      { zh: '藥膏', tw: '藥膏', lo: 'io̍h-ko' },
  painkiller:    { zh: '止痛藥', tw: '止疼藥', lo: 'tsí-thiànn io̍h' },
  herbal_pack:   { zh: '中藥包', tw: '漢藥包', lo: 'hàn-io̍h-pau' },
  bone_pill:     { zh: '狗狗藥', tw: '狗仔藥', lo: 'káu-á io̍h' },
  fish_pill:     { zh: '貓咪藥', tw: '貓仔藥', lo: 'niau-á io̍h' },
  oil_can:       { zh: '機油', tw: '機油', lo: 'ki-iû' },
  battery:       { zh: '電池', tw: '電池', lo: 'tiān-tî' },

  /* 病人 */
  kid_twintail_girl:    { zh: '雙馬尾小女生', tw: '雙毛尾仔查某囡仔', lo: 'siang-mn̂g-bué-á tsa-bóo gín-á' },
  kid_cap_boy:          { zh: '棒球帽小男生', tw: '戴帽仔的查埔囡仔', lo: 'tì bō-á ê tsa-poo gín-á' },
  toddler_boy_plush:    { zh: '抱玩偶的小小男生', tw: '抱尪仔的弟弟', lo: 'phō ang-á ê tī-tī' },
  toddler_girl_plush:   { zh: '抱玩偶的小小女生', tw: '抱尪仔的妹妹', lo: 'phō ang-á ê muē-muē' },
  teen_guitar_boy:      { zh: '吉他哥哥', tw: '吉他阿兄', lo: 'gì-tah a-hiann' },
  teen_bookish_girl:    { zh: '讀書姐姐', tw: '讀冊阿姊', lo: 'tha̍k-tsheh a-tsí' },
  adult_office_dad:     { zh: '上班族爸爸', tw: '上班的阿爸', lo: 'siōng-pan ê a-pah' },
  adult_sporty_mom:     { zh: '運動媽媽', tw: '運動阿母', lo: 'ūn-tōng a-bú' },
  adult_office_mom:     { zh: '上班族媽媽', tw: '上班的阿母', lo: 'siōng-pan ê a-bú' },
  adult_apron_dad:      { zh: '圍裙爸爸', tw: '圍裙阿爸', lo: 'uî-kûn a-pah' },
  elder_cane_grandpa:   { zh: '拄拐杖的阿公', tw: '托枴仔的阿公', lo: 'thuh kuái-á ê a-kong' },
  elder_perm_grandma:   { zh: '燙捲髮的阿媽', tw: '電頭毛的阿媽', lo: 'tiān thâu-mn̂g ê a-má' },
  elder_farmer_grandpa: { zh: '農夫阿公', tw: '作穡阿公', lo: 'tsoh-sit a-kong' },
  elder_fisher_grandma: { zh: '漁夫阿媽', tw: '討海阿媽', lo: 'thó-hái a-má' },
  dog:      { zh: '狗', tw: '狗仔', lo: 'káu-á' },
  cat:      { zh: '貓', tw: '貓仔', lo: 'niau-á' },
  rabbit:   { zh: '兔子', tw: '兔仔', lo: 'thòo-á' },
  sheep:    { zh: '羊', tw: '綿羊', lo: 'mî-iûnn' },
  monkey:   { zh: '猴子', tw: '猴山仔', lo: 'kâu-san-á' },
  bird:     { zh: '鳥', tw: '鳥仔', lo: 'tsiáu-á' },
  raccoon:  { zh: '浣熊', tw: '浣熊', lo: 'uán-hîm' },
  elephant: { zh: '大象', tw: '象', lo: 'tshiūnn' },
  giraffe:  { zh: '長頸鹿', tw: '麒麟鹿', lo: 'kî-lîn-lo̍k' },
  rhino:    { zh: '犀牛', tw: '犀牛', lo: 'sai-gû' },
  lion:     { zh: '獅子', tw: '獅', lo: 'sai' },
  tiger:    { zh: '老虎', tw: '虎', lo: 'hóo' },
  dinosaur: { zh: '恐龍', tw: '恐龍', lo: 'khióng-liông' },
  unicorn:  { zh: '獨角獸', tw: '獨角獸', lo: 'to̍k-kak-siù' },
  robot:    { zh: '機器人', tw: '機器人', lo: 'ki-khì-lâng' },

  /* NPC */
  reception_npc: { zh: '櫃台助理', tw: '櫃台助理', lo: 'kuī-tâi tsōo-lí' },
  nurse:         { zh: '護理師', tw: '護理師', lo: 'hōo-lí-su' },
  doc_internal:  { zh: '內科醫生', tw: '內科醫', lo: 'lāi-kho-i' },
  doc_ent:       { zh: '耳鼻喉科醫生', tw: '耳鼻喉科醫', lo: 'hīnn-phīnn-âu-i' },
  doc_dental:    { zh: '牙醫', tw: '齒科醫', lo: 'khí-kho-i' },
  doc_surgery:   { zh: '外科醫生', tw: '外科醫', lo: 'guā-kho-i' },
  doc_tcm:       { zh: '中醫師', tw: '漢醫', lo: 'hàn-i' },
  doc_vet:       { zh: '獸醫', tw: '獸醫', lo: 'siù-i' },
  doc_repair:    { zh: '工程師', tw: '工程師', lo: 'kang-tîng-su' },
  pharmacist:    { zh: '藥師', tw: '藥師', lo: 'io̍h-su' },
};
